package org.hydev.themeapplytools.utils

import android.app.Activity
import android.app.DownloadManager
import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.net.Uri
import android.os.Environment
import android.widget.Toast
import com.google.android.material.dialog.MaterialAlertDialogBuilder

object FileUtils {
    /**
     * Copy any message (link) to clipboard.
     *
     * @param link message needs to copy.
     */
    fun copyLink(activity: Activity, link: String?) {
        val clipboardManager = activity.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clipData = ClipData.newPlainText("downloadLink", link)
        clipboardManager.setPrimaryClip(clipData)
        Toast.makeText(activity, "已复制到剪切版", Toast.LENGTH_LONG).show()
    }

    /**
     * Download theme via system download manager.
     * It seems cannot work on AOSP-like ROM...
     *
     * @param themeInfo theme info set generated by ThemeUtils.getThemeInfo.
     * @see ThemeUtils.getThemeInfo
     */
    fun systemDownload(activity: Activity, themeInfo: ThemeUtils.MiuiThemeData) {
        val request = DownloadManager.Request(Uri.parse(themeInfo.getDownloadUrl()))
        request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED)

        Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).mkdir()
        request.setDestinationInExternalPublicDir("Download", themeInfo.getFileName())

        (activity.getSystemService(Context.DOWNLOAD_SERVICE) as DownloadManager).enqueue(request)
        Toast.makeText(activity, "已开始下载", Toast.LENGTH_LONG).show()
    }

    /**
     * Create an alert
     */
    fun alert(activity: Activity, title: String, message: String): MaterialAlertDialogBuilder {
        return MaterialAlertDialogBuilder(activity).setTitle(title).setMessage(message.trimIndent())
    }

    /**
     * Show info alert
     */
    fun alertInfo(activity: Activity, title: String, message: String) {
        activity.runOnUiThread { alert(activity, title, message).setPositiveButton("OK", null).show() }
    }
}
